### ISSUE TITLE
Awesome...working in newer versions of OS X and macOS?

### ISSUE THREAD

**Issue by jacobsalmela** [ipat8/Single-User-Mode-Protection-Agent#1]
I recall that loading certain things in SUM was no longer possible.  I think Apple put some sort of protection in against it...what version(s) do you have this running on?

**Comment by ipat8** [comment]
The latest that this is confirmed to be working on is 10.12. I'm going to start validation for 10.13 later this month.

**Comment by ipat8** [comment]
Confirmed support for SUM script in Beta 6 of macOS 12.13. SUM script does not seem to require user to disable SIP.
